languaje: python
python:
 - "3.5"
# command to install dependencies
install: #"pip install -r requirements.txt"
#- pip install -r requirements.txt

#- python3 -m pip install --upgrade pip
- pip install --user mock==2.0
- pip install --user coverage
#- pip
# command to run tests
script:
- coverage run test.py
- coverage report
